// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzn4Ttsyjsr39AMSlMSQjN6jq4tojM2UA',
    appId: '1:45123575748:web:68204aad492ad848d08e91',
    messagingSenderId: '45123575748',
    projectId: 'doan-83752',
    authDomain: 'doan-83752.firebaseapp.com',
    storageBucket: 'doan-83752.firebasestorage.app',
    measurementId: 'G-PFLCECWVCF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG9HvHc7QRo9wJNvCxwmrVZX2uO886i-w',
    appId: '1:45123575748:android:1e6a9b14e9236183d08e91',
    messagingSenderId: '45123575748',
    projectId: 'doan-83752',
    storageBucket: 'doan-83752.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDolHtsKgYW7rFG5s-4fHb8lEdHxs_d8V0',
    appId: '1:45123575748:ios:e77be57aa9bb0ac6d08e91',
    messagingSenderId: '45123575748',
    projectId: 'doan-83752',
    storageBucket: 'doan-83752.firebasestorage.app',
    iosBundleId: 'com.example.doAn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDolHtsKgYW7rFG5s-4fHb8lEdHxs_d8V0',
    appId: '1:45123575748:ios:e77be57aa9bb0ac6d08e91',
    messagingSenderId: '45123575748',
    projectId: 'doan-83752',
    storageBucket: 'doan-83752.firebasestorage.app',
    iosBundleId: 'com.example.doAn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzn4Ttsyjsr39AMSlMSQjN6jq4tojM2UA',
    appId: '1:45123575748:web:31295086689bd055d08e91',
    messagingSenderId: '45123575748',
    projectId: 'doan-83752',
    authDomain: 'doan-83752.firebaseapp.com',
    storageBucket: 'doan-83752.firebasestorage.app',
    measurementId: 'G-714F16ZR94',
  );
}
